# Script to generate the HTML for the FAQ page questions and answers

# Define the list of questions and answers (text or raw HTML supported)
# -------------------Edit the questions and answers below------------------- #
questionsAndAnswers = [
    ["What is the answer to question 1?","This is my answer to question 1."],
    ["What is the answer to question 2?","This is my answer to question 2."],
    ["What is the answer to question 3?","This is my answer to question 3."],
    ["What is the answer to question 4?","This is my answer to question 4."]
]
# -------------------Edit the questions and answers above------------------- #


# Template HTML for each question and answer
template = """
        <div class="FAQ_question">
            <div class="FAQ_question-bar" onclick="hideShow_FAQ_answer(event)">
                <span class="FAQ_Question_hideShow" id="FAQ_hideShow">&#9650;</span>
                {question}
            </div>
            <div class="FAQ_answer" style="display: none;">
                {answer}
            </div>
        </div>"""

# Initialize the HTML string
html = ""
# Loop through the questions and answers and add them to the HTML string
for question, answer in questionsAndAnswers:
    html += template.format(question=question, answer=answer)

# Save the HTML string to file
with open("homepage_edits/FAQ_and_ContactUs/FAQs_AutoGeneratedCards.html", "w") as f:
    f.write(html)

print("HTML generated successfully!")