# Script to generate the HTML for the FAQ page questions and answers


# Import questions and answers from a txt file (homepage_edits\FAQ_and_ContactUs\FAW_questions.txt)
# First line is the question, second line is the answer, third line is a blank line
questionsAndAnswers = []
with open("homepage_edits/FAQ_and_ContactUs/FAQ_questions.txt", "r") as f:
    lines = f.readlines()
    for i in range(0, len(lines), 3):
        questionsAndAnswers.append([lines[i].strip(), lines[i+1].strip()])


# Template HTML for each question and answer
template = """
        <div class="FAQ_question">
            <div class="FAQ_question-bar" onclick="hideShow_FAQ_answer(event)" active="false">
                <span class="FAQ_Question_hideShow" id="FAQ_hideShow">&#9650;</span>
                {question}
            </div>
            <div class="FAQ_answer" style="display: none;">
                {answer}
            </div>
        </div>"""

# Initialize the HTML string
html = ""
# Loop through the questions and answers and add them to the HTML string
for question, answer in questionsAndAnswers:
    html += template.format(question=question, answer=answer)

# Save the HTML string to file
with open("homepage_edits/FAQ_and_ContactUs/FAQs_AutoGeneratedCards.html", "w") as f:
    f.write(html)

print("\nHTML generated successfully!\n")